name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Secrets
        run: |
          echo "CPANEL_HOST=${{ secrets.CPANEL_HOST }}"
          echo "CPANEL_USER=${{ secrets.CPANEL_USER }}"
          echo "SSH_PRIVATE_KEY Length: ${#SSH_PRIVATE_KEY}"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup SSH Key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.CPANEL_HOST }}" >> $HOME/.ssh/known_hosts

      - name: Deploy to cPanel via SCP
        run: |
          scp -r * ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }}:public_html/elec-main

      - name: Run Laravel Setup Commands on cPanel
        run: |
          ssh ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }} << 'EOF'
          cd /home/${{ secrets.CPANEL_USER }}/public_html/elec-main
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan storage:link
          php artisan swagger-lume:generate
          EOF
