name: Fleet Management System Deployment

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.CPANEL_HOST }}" >> $HOME/.ssh/known_hosts

      - name: SSH into cPanel and Pull Latest Code
        run: |
          ssh ${{ secrets.CPANEL_USER }}@${{ secrets.CPANEL_HOST }} << 'EOF'
          cd /home/${{ secrets.CPANEL_USER }}/public_html/elec-main
          git reset --hard  # Ensure a clean state
          git pull origin main  # Pull latest changes
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan storage:link
          php artisan l5-swagger:generate
          EOF
